app/urls.py
# -*- encoding: utf-8 -*-
"""
License: MIT
Copyright (c) 2019 - present AppSeed.us
"""

from django.urls import path, re_path
from app import views
from app.views import *
from campaign.views import *

urlpatterns = [
    # Matches any html file 
    re_path(r'^.*\.html', views.pages, name='pages'),

    # The home page
    path('', views.index, name='home'),
    path('campaign/',campaign, name='campaign'),
    path('donation/', views.donation, name='donation'),
    path('update_profile/<str:pk>/', views.updateProfile, name="update_profile"),
    path('salaTime/<str:pk>/', views.salaTime, name="salaTime"),
    

]

core/urls.py
# -*- encoding: utf-8 -*-
"""
License: MIT
Copyright (c) 2019 - present AppSeed.us
"""

from django.contrib import admin
from django.urls import path, include  # add this
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("authentication.urls")),  # add this
    path("", include("app.urls")),
    path('', include('users.urls')),
    path('', include('masjid.urls')),
    path('', include('campaign.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG: # new
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

masjid/urls.py
from rest_framework import routers
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from masjid.views import MasjidViewSet, SalahTimeViewSet, getAllMasjid


router = routers.DefaultRouter()
router.register('masjid_list', MasjidViewSet)
router.register('salah_time', SalahTimeViewSet)

urlpatterns = [ 
    path('', include(router.urls)),
    path('getMasjidList', getAllMasjid, name="getAllMasjid"),  
    
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from rest_framework import routers
from .views import CustomUserViewSet, RegisterUserViewSet, login ,FeedbackViewSet, getCardDetail, getCard, activeDonation, donationStatus, getDonation, updateDonation
from users.views import updateCardDetail, UpdateUserProfileViewSet, verifyPhoneView, donationForCampaign, donationForMasjid, donationHistory, stopRecurringDonation, forgetPin, updatePin
from users import views

router = routers.DefaultRouter()
router.register('users', RegisterUserViewSet)
router.register('feedback', FeedbackViewSet)
router.register('updateProfileImage', UpdateUserProfileViewSet)

urlpatterns = [
    path('rest-auth/', include('rest_auth.urls')),
    path('user/login', login, name="login"),
    path('cardDetail', getCardDetail, name="getCardDetail"),
    path('getCard', getCard, name="getCard"),
    path('updateCardDetail', updateCardDetail, name="updateCardDetail"),
    path('verifyPhoneView', verifyPhoneView, name="verifyPhoneView"),
    path('donationForCampaign', donationForCampaign, name="donationForCampaign"),
    path('donationForMasjid', donationForMasjid, name="donationForMasjid"),
    path('donationHistory', donationHistory, name="donationHistory"),
    path('activeDonation', activeDonation, name="activeDonation"),
    path('donationStatus', donationStatus, name="donationStatus"),
    path('stopRecurringDonation', stopRecurringDonation, name="stopRecurringDonation"),
    path('getDonation', getDonation, name="getDonation"),
    path('updateDonation', updateDonation, name="updateDonation"),
    path('forgetPin', forgetPin, name="forgetPin"),
    path('updatePin', updatePin, name="updatePin"),
    
    
    
    
    path('', include(router.urls)),
    
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from datetime import date


class CustomUser(AbstractUser):
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username']
    username = models.CharField(max_length=100, unique=False, null=True, blank=True)
    email = models.EmailField(unique=True, null=False)
    name = models.CharField(max_length=100, null=True)
    phone = models.CharField(max_length=35, null=False)
    gender = models.CharField(max_length=50, null=True)
    dob = models.DateField(null=True, auto_now = False)
    address  = models.CharField(max_length=500, null=True)
    status  = models.BooleanField(default=False)
    masjid_name = models.CharField(max_length=255, null=True)
    masjid_id = models.IntegerField(null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    card_info = models.BooleanField(default=False)
    cardName = models.CharField(max_length=55, null=True)
    donation_reference = models.CharField(max_length=50, null=True)
    updated_at = models.DateTimeField(null = True)
    stripe_customer_id = models.CharField(max_length=255, null=True)
    card_token = models.CharField(max_length=100, null=True)
    masjidCardName = models.CharField(max_length=100, null=True)
    verify_user  = models.BooleanField(default=False)
    masjidCardNumber = models.CharField(max_length=100, null=True)
    masjidAddress  = models.CharField(max_length=500, null=True)
    lat = models.CharField(max_length=100, null=True)
    lng = models.CharField(max_length=100, null=True)
    profile_pic = models.ImageField(upload_to='profile_pic', null=True)

    @property
    def full_name(self):
        name = ''
        if self.first_name:
            name += self.first_name
        if self.last_name:
            name += " " + self.last_name

        return name



class Feedback(models.Model):
    user_id = models.ForeignKey(CustomUser, on_delete=models.CASCADE, related_name='user_id')
    comment = models.CharField(max_length=250, null=True)
    feedback = models.FloatField(null=False)
    created_at = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.userid.email

class Donation(models.Model):
    userId = models.IntegerField(null=True)
    object_id = models.CharField(max_length=255, null=True)
    masjid_id = models.IntegerField(null=True)
    amount = models.CharField(max_length=255, null=True)
    donation_reference = models.CharField(max_length=50, null=True)
    donation_for = models.CharField(max_length=50, null=True)
    payment_type = models.CharField(max_length=50, null=False)
    recurring_period = models.CharField(max_length=50, null=True)
    detail = models.CharField(max_length=255, null=True)
    starting_at = models.DateField(auto_now=False, null=True)
    next_at = models.DateField(auto_now=False, null=True)
    payment_status = models.BooleanField(default=True)
    charge_id = models.CharField(max_length=255, null=True)
    customer_id = models.CharField(max_length=255, null=True)
    cardToken = models.CharField(max_length=500, null=True)
    created_at = models.DateField(auto_now_add=True)
    updated_at = models.DateField(null = True)

campaign/forms.py
from django import forms
from users.models import CustomUser
from .models import Campaign, CampaignFiles

class addCampaignForm(forms.ModelForm):
    image1 = forms.ImageField(required=False, widget=forms.FileInput(attrs={'id': 'add-image', 'class':'fusk'}))
    # Confirm_password = forms.CharField(required=False, widget=forms.PasswordInput(attrs={'placeholder': 'Confirm Password'}))
    # masjidCardNumber = forms.CharField(required=False, widget=forms.TextInput(attrs={'placeholder': '0000 0000 0000 0000'}))
    # masjidCardName = forms.CharField(required=False, widget=forms.TextInput(attrs={'placeholder': 'Jhon Doe'}))
    # title = forms.CharField(required=False, widget=forms.TextInput(attrs={'placeholder': 'title'}))
    # phone= forms.CharField(required=False, widget=forms.TextInput(attrs={'type': 'tel', 'class':'getphone', }))
    # profile_pic= forms.CharField(required=False, widget=forms.TextInput(attrs={'type': 'file' }))
    
    class Meta:
        model = Campaign
        fields = ('title',)
        labels = {}
    # def __init__(self, *args, **kwargs):
    #     super(addCampaignForm, self).__init__(*args, **kwargs)
    #     for visible in self.visible_fields():
    #         visible.field.widget.attrs['class'] = 'form-control'

campaign/views.py
from django.shortcuts import render
from campaign.serializers import CampaignSerializer, CampaignFilesSerializer
from campaign.models import Campaign, CampaignFiles
from rest_framework import viewsets
from django.http import HttpResponse, JsonResponse
from rest_framework.response import Response
from rest_framework.decorators import parser_classes
from django.contrib.auth.decorators import login_required
import requests
from users.models import CustomUser
from campaign.forms import addCampaignForm
from django.views.decorators.csrf import csrf_protect
from masjid.models import Masjid
import datetime
from rest_framework import status
from rest_framework.decorators import api_view
from datetime import date

class CampaignViewsets(viewsets.ModelViewSet):
    serializer_class = CampaignFilesSerializer
    queryset = CampaignFiles.objects.all()


class CampaignFilesViewSet(viewsets.ModelViewSet):
    serializer_class = CampaignSerializer
    queryset = Campaign.objects.all()

@login_required(login_url="/login/")
def campaign(request):
    user = request.user
    if request.user.is_superuser:
        context = {}
        return render(request, "superAdmin/campaign-a.html",context)
    else:
        all_campaign = Campaign.objects.filter(userId=user.id)
        context = {"all_campaign":all_campaign}
        return render(request, "campaign.html",context)

@login_required(login_url="/login/")
def addCampaign(request):
    user = request.user.id
    msg = None
    msg1 = None
    if request.method == 'POST':
        try:
            masjid_id = Masjid.objects.get(masjid_user=user)
        except Masjid.DoesNotExist:
            masjid_id = None
        files = request.FILES
        title = request.POST.get("title",None)
        target_amount = request.POST.get("target_amount",None)
        raised_amount = request.POST.get("raised_amount",None)
        start_date = request.POST.get("start_date",None)
        end_date = request.POST.get("end_date",None)
        detail = request.POST.get("campaign_detail",None)
        target_amount = int(target_amount)
        raised_amount = int(raised_amount)
        if target_amount > raised_amount:
            msg1 = "Error! Target amount must be less or equal to raised amount."
        else:
            campaign = Campaign.objects.create(title=title, target_amount=target_amount, raised_amount=raised_amount, start_date=start_date, end_date=end_date, detail=detail, masjid_id=masjid_id, userId=user)
            if campaign:
                get_campaign = Campaign.objects.get(id=campaign.id)
                if files:
                    img1 = files.get("image", None)
                    img2 = files.get("image1", None)
                    img3 = files.get("image2", None)
                    video1 = files.get("video", None)
                    video2 = files.get("video1", None)
                    video3 = files.get("video2", None)
                    all_files = [[img1, video1], [img2, video2], [img3, video3]]
                    for obj in all_files:
                        im = obj[0]
                        vi = obj[1]
                        if im or vi is not None:
                            CampaignFiles.objects.create(image=im, video=vi, campaign=get_campaign)
                msg = 'Campaign added successfully.'
        data = {'msg': msg, 'msg1': msg1}
        return JsonResponse(data)
    else:
        return HttpResponse('Request method is not a POST')

@api_view(['GET'])
def getAllCampaign(request):
    if request.method == 'GET':
        all_campaign =  Campaign.objects.all()
        campaignList = []
        campaignDict = {}
        today = date.today()
        current_date = today.strftime("%Y-%m-%d")
        if all_campaign:
            for obj in all_campaign:
                endDate = str(obj.end_date)
                if endDate >= current_date:
                    try:
                        get_campaign = Campaign.objects.get(id=obj.id)
                    except Campaign.DoesNotExist:
                        get_campaign = None
                    if get_campaign:
                        allCampaignFiles =  CampaignFiles.objects.filter(campaign=get_campaign)
                        campaignFilesList = []
                        campaignFilesDict = {}
                        try:
                            masjid = Masjid.objects.get(id=obj.masjid_id.id)
                        except Masjid.DoesNotExist:
                            masjid = None
                        if allCampaignFiles:
                            for obj1 in allCampaignFiles:
                                if not obj1.image and obj1.video:
                                    campaignFilesDict = {
                                        "id":obj1.id,
                                        "image":None,
                                        "video":obj1.video.url,
                                        "campaign": get_campaign.id
                                    }
                                elif obj1.image and not obj1.video:
                                    campaignFilesDict = {
                                        "id":obj1.id,
                                        "image":obj1.image.url,
                                        "video":None,
                                        "campaign": get_campaign.id
                                    }
                                elif not obj1.image and not obj1.video:
                                    campaignFilesDict = {
                                        "id":obj1.id,
                                        "image":None,
                                        "video":None,
                                        "campaign": get_campaign.id
                                    }
                                else:
                                    campaignFilesDict = {
                                        "id":obj1.id,
                                        "image":obj1.image.url,
                                        "video":obj1.video.url,
                                        "campaign": get_campaign.id
                                    }
                                campaignFilesList.append(campaignFilesDict)
                            campaignDict = {
                                "id":obj.id,
                                "title":obj.title,
                                "target_amount":obj.target_amount,
                                "raised_amount":obj.raised_amount,
                                "start_date":obj.start_date,
                                "end_date":obj.end_date,
                                "detail":obj.detail,
                                "masjid_id":obj.masjid_id.id,
                                "campaign_data":campaignFilesList,
                            }
                            campaignList.append(campaignDict)
                        else:
                            campaignDict = {
                                "id":obj.id,
                                "title":obj.title,
                                "target_amount":obj.target_amount,
                                "raised_amount":obj.raised_amount,
                                "start_date":obj.start_date,
                                "end_date":obj.end_date,
                                "detail":obj.detail,
                                "masjid_id":obj.masjid_id.id ,
                                "campaign_data":campaignFilesList,
                            }
                            campaignList.append(campaignDict)
            return Response(
                campaignList
            )
        else:  
            return Response({
                campaignList
            })
    else:
        return Response({
            "status": status.HTTP_400_BAD_REQUEST,
            "message": "Method not allowed",
        })


# past_date = "2021-04-05"
# today = date.today()
# current_date = today.strftime("%Y-%m-%d")
# print(current_date)
# if current_date < past_date:
#     print(True)
# else:
#     print(False)

core/templates/dashboard.html
{% extends "layouts/base.html" %}
{% block title %} Dashboard {% endblock title %}

<!-- Specific CSS goes HERE -->
{% block stylesheets %}
<link rel="stylesheet" href="/static/assets/css/index.css">
<link rel="stylesheet" href="https://cdn.datatables.net/1.10.22/css/jquery.dataTables.min.css">
<link rel="stylesheet" href="https://cdn.datatables.net/select/1.3.1/css/select.dataTables.min.css">
{% endblock stylesheets %}

{% block content %}

    <div class="container-fluid pb-5">
      <div class="row">
        <div class="col-md-12" style="text-align: center;">
          <h2 class="page-title">Dashboard</h2>
        </div>
      </div>
    </div>
    <div class="page-inner mt--5">
      <div class="row mt--2">
        <div class="col-md-6">
          <div class="card full-height msg-card-body">
            <div class="card-body text-center">
              <img src="/static/assets/img/message.png"  alt="">
              <div class="content-box">
                <div class="title">Messages</div>
              </div>
            </div>
          </div>
        </div>
        <div class="col-md-6">
          <div class="card full-height msg-card-body">
            <div class="card-body text-center">
              <img src="/static/assets/img/employee1.png" alt="">
              <div class="content-box">
                <div class="title">All Employees</div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="row row-card-no-pd">
        <div class="col-md-12">
          <div class="card msg-card-body">
            <div class="card-body text-center">
              <img src="/static/assets/img/chart-d.png" style="width: 100%;" alt="">
            </div>
          </div>
        </div>
      </div>
    </div>

{% endblock content %}

{% block javascripts %}

	<script src="/static/assets/js/demo.js"></script>

  <script>
    $(document).ready(function() {
        $('#datatable').DataTable();
    } );
    $('#datatable').DataTable( {
        responsive: true
    } );
  </script>

{% endblock javascripts %}

core/templates/error-500.html
{% extends "layouts/base.html" %}

{% block title %} 500 Error {% endblock title %}

<!-- Specific CSS goes HERE -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

    <br />
    <br />
    
    <h2>SORRY!</h2>
    <h3 class="font-weight-light">Server Error.</h3>

{% endblock content %}

<!-- Specific JS goes HERE -->
{% block javascripts %}{% endblock javascripts %}

core/templates/setting.html
{% extends "layouts/base.html" %}
{% block title %} Dashboard {% endblock title %}
{% block stylesheets %}
<link rel="stylesheet" href="/static/assets/css/profile.css">
<style>
  .alert .close {
    background: rgb(255 255 255 / 0%);
    width: 25px;
    height: 25px;
    line-height: 25px;
    top: 0px!important;
    color: black;
    border-radius: 50%;
  }
</style>
{% endblock stylesheets %}

{% block content %}

    <div class="container-fluid pb-5">
      <div class="row">
        <div class="col-md-12" style="text-align: center;">
          <h2 class="page-title">Profile</h2>
        </div>
      </div>
    </div>
    <div class="page-inner mt--5">
      <div class="row mt--2">
      </div>
      <div class="row row-card-no-pd">
        <div class="col-md-12">
            <div class="container">
                <div class="row pt-2 pb-2">
                    <div class="col-md-1"></div>
                    <div class="col-md-10">
                        <div class="card p-4" id="update-profile">
                          {% if msg %}
                          <div class="alert alert-warning alert-dismissible fade show" style="background-color: #ffeced;border: none;box-shadow: none;" role="alert">
                            Error! {{msg}}
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                              <span aria-hidden="true">&times;</span>
                            </button>
                          </div>
                          {% endif %}
                          {% if msg1 %}
                          <div class="alert alert-warning alert-dismissible fade show" style="background-color: #daf1f7;border: none;box-shadow: none;" role="alert">
                            {{msg1}}
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                              <span aria-hidden="true">&times;</span>
                            </button>
                          </div>
                          {% endif %}                  
                            <input type="hidden" id="succescase" value="{{msg1}}">
                            <!-- {% if request.user.profile_pic %}
                            <div class="text-center pb-2">
                                <img class="profile-m" src="{{request.user.profile_pic.url}}" alt="profile">
                            </div>
                            {% else %}
                            <div class="text-center pb-2">
                              <img class="profile-m" src="/static/assets/img/black1.png" alt="profile">
                            </div>
                            {% endif %} -->
                            <form action="" method="POST" enctype="multipart/form-data" id="signup-form">
                              {% csrf_token %}
                                <div class="row">
                                  <div class="col-md-6">
                                    <div class="form-group">
                                      <label for="">Masjid Name</label>
                                      {{form1.masjid_name}}
                                      <!-- <input type="text" name="name" class="form-control" placeholder="John doe" required> -->
                                    </div>
                                  </div>
                                  <div class="col-md-6">
                                    <div class="form-group">
                                      <label for="">Email</label>
                                      {{form1.email}}
                                      <!-- <input type="email" class="form-control" name="email" placeholder="jhondoe@gmail.com" required> -->
                                    </div>
                                  </div>
                                </div>
                                <div class="row">
                                  <div class="col-md-6">
                                    <div class="form-group">
                                      <label for="">Phone Number</label>
                                      <!-- <input type="tel" class="form-control getphone" name="phone_number" id="phone_number" value="{{phone}}" required/> -->
                                      {{form1.phone}}
                                      <span class="tel-error" style="color: #dc3545;display: none;">Please enter only numbers</span>
                                    </div>
                                  </div>
                                  <div class="col-md-6">
                                    <div class="form-group">
                                      <label for="">Trust Account Name</label>
                                      <!-- <input type="text" name="account_name"  class="form-control" placeholder="Asaan Account" required> -->
                                      {{form1.masjidCardName}}
                                    </div>
                                  </div>
                                </div>
                                <div class="row">
                                  {% if user.profile_pic %}
                                  <div class="col-md-6">
                                    <div class="form-group" style="margin-top: 21px;">
                                      <label for="">Trust Account Number</label>
                                      <!-- <input type="number" class="form-control" name="account_number" required placeholder="0000 0000 0000 0000"/> -->
                                      {{form1.masjidCardNumber}}
                                    </div>
                                  </div>
                                  {% else %}
                                  <div class="col-md-6">
                                    <div class="form-group">
                                      <label for="">Trust Account Number</label>
                                      <!-- <input type="number" class="form-control" name="account_number" required placeholder="0000 0000 0000 0000"/> -->
                                      {{form1.masjidCardNumber}}
                                    </div>
                                  </div>
                                  {% endif %}
                                  <div class="col-md-6">
                                    <div class="form-group">
                                      <label for="">Profile Picture</label>
                                      <!-- <input type="file" class="form-control filetype"> -->
                                      {{form1.profile_pic}}
                                    </div>
                                  </div>
                                </div>
                                <div class="row">
                                  <div class="col-md-6">
                                    <div class="form-group">
                                      <label for="">Current Password</label>
                                      <!-- <input type="password" class="form-control" name="current_password" class="password" required placeholder="current password"/> -->
                                      {{form1.Current_password}}
                                    </div>
                                  </div>
                                  <div class="col-md-6">
                                    <div class="form-group">
                                      <label for="">New Password</label>
                                      <!-- <input type="password" class="form-control" name="new_password" class="password" required placeholder="new password"/> -->
                                      {{form1.New_password}}
                                    </div>
                                  </div>
                                </div>
                                <div class="row">
                                  <div class="col-md-6">
                                    <div class="form-group">
                                      <label for="">Confirm Password</label>
                                      <!-- <input type="password" class="form-control" name="confirm_password" class="password" required placeholder="confirm password"/> -->
                                      {{form1.Confirm_password}}
                                    </div>
                                  </div>
                                  <div class="col-md-6">
                                    <div class="form-group">
                                      <label for=""></label>
                                      <input type="submit" class="form-control submitbtn" value="SAVE"/>
                                    </div>
                                  </div>
                                </div>
                            </form>
                        </div>
                    </div>
                    <div class="col-md-1"></div>
                </div>
            </div>
        </div>
      </div>
    </div>
    <!-- <script src="http://code.jquery.com/jquery-1.9.1.js"></script> -->
{% endblock content %}

{% block javascripts %}

<!-- <script src="/static/assets/js/demo.js"></script> -->
<script>
  $.ajax({
      url: "http://ip-api.com/json",
      jsonpCallback: "callback",
      dataType: "jsonp",
      success: function( response ) {
          var phone_number = window.intlTelInput(document.querySelector("#id_phone"), {
              separateDialCode: true,
              preferredCountries: [response.countryCode],
              hiddenInput: "full",
              utilsScript: "//cdnjs.cloudflare.com/ajax/libs/intl-tel-input/17.0.3/js/utils.js"

          });
          var countrycode = phone_number.s["dialCode"];
          $('#id_phone').on('change paste keyup', function(){
              var inputnum = $(this).val();
              // console.log(inputnum)  
              // var onlynumbers = /^[0-9]+$/; 
              var onlynumbers = /^[\d\\+ ]+$/;
              if(inputnum.match(onlynumbers)){
                $(".tel-error").hide();
              }else{
                $(".tel-error").show();
                return false;
              }
              
          });
          // console.log($('#phone_number').val());
          // console.log(phone_number.s["dialCode"]);
          $("#signup-form").submit(function(){
            var full_number = phone_number.getNumber(intlTelInputUtils.numberFormat.E164);
            $("input[name='phone'").val(full_number);
          });
      }
  });
  $(document).ready(function(){
    var succescase = $("#succescase").val();
    if (succescase == "Profile updated successfully."){
      setTimeout(function(){ 
        var origin   = window.location.origin;
        window.location.replace(origin);
      }, 2000);
    }
  });
</script>

{% endblock javascripts %}